default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: portfolio_development
  username: postgres  # DockerのPostgreSQLはデフォルトで `postgres` ユーザー
  password: password  # `docker-compose.yml` に設定したパスワード
  host: db            # `localhost` ではなく `db` にする！

test:
  <<: *default
  database: portfolio_test
  username: postgres
  password: password
  host: db

production:
  <<: *default
  database: portfolio_production
  username: app
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>
  host: db

